<a href="https://colab.research.google.com/github/ArunadeviRamesh/FORECASTING-SPREAD-OF-COVID-19-FOR-TOP-AFFECTED-REGIONS-USING-MULTIVARIATE-LINEAR-REGRESSION/blob/main/FORECASTING_THE_SPREAD_OF_COVID_USING_REGRESSION_ALGORITHM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objs as go
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

TAMILNADU

In [4]:
df=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/covid data/tamilnadu/TN confirmed and active 15 and 5 days.csv")
df.head(3)

district      date  ...  confirmed one week  death one week
0  Tamil Nadu  7/3/2020  ...                   1               0
1  Tamil Nadu  8/3/2020  ...                   1               0
2  Tamil Nadu  9/3/2020  ...                   1               0

[3 rows x 10 columns]

In [5]:
x=df.iloc[:,[3,4]]
y=df.iloc[:,6]


In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))

Accuracy r2_score 99.35727879948986
ACCURACY= 99.51119975778796
MAE= 2628.670579847324
MSE= 15867541.115836555
Final rmse value is = 3983.408228619878


In [8]:
print(lr.predict([[175678,2551]]))
print(lr.predict([[185678,3500]]))
lr.predict([[180643,2626]])

[283717.51614998]
[249925.67090885]


array([291515.62695303])

WORLD DATASET

In [9]:
df=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/covid data/world/world 15 and 5.csv")
df.head(3)

district        date  active  ...  death 15  confirmed 5  death 5
0    World  12/31/2019     NaN  ...         2           59        0
1    World    1/1/2020     NaN  ...         2           59        0
2    World    1/2/2020     NaN  ...         2           59        0

[3 rows x 10 columns]

In [10]:
x=df.iloc[:,[3,4]]
y=df.iloc[:,6]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))

Accuracy r2_score 99.55963764911255
ACCURACY= 99.57346092775042
MAE= 215662.56037337764
MSE= 82479060625.78702
Final rmse value is = 287191.6792419081


In [12]:
lr.predict([[14684741,610110]])

array([18744939.40021707])

USA

In [17]:
df=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/covid data/USA/USA 15 and 5.csv")
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,6]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))

Accuracy r2_score 99.02464964320981
ACCURACY= 99.1440894488326
MAE= 96256.7407080868
MSE= 12645202497.403793
Final rmse value is = 112450.88926906622


In [18]:
lr.predict([[3830010,140906]])

array([5905644.91969191])

UK

In [20]:
df=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/covid data/UK/UK 15 and 5.csv")
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,6]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))
lr.predict([[294066,45273]])

Accuracy r2_score 93.7993617360116
ACCURACY= 95.93174298823104
MAE= 25281.645721886383
MSE= 1015625384.4986631
Final rmse value is = 31868.877992465677


array([365408.09432113])

ITALY

In [22]:
df=pd.read_csv('/content/drive/MyDrive/Machine Learning Projects/covid data/Italy/Italy 5 and 15.csv')
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,6]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))
lr.predict([[244624,35058]])

Accuracy r2_score 98.82691705355336
ACCURACY= 98.30236705146372
MAE= 8898.094549675781
MSE= 120458852.22278853
Final rmse value is = 10975.37481012783


array([246179.89768425])

INDIA

In [23]:
df=pd.read_csv('/content/drive/MyDrive/Machine Learning Projects/covid data/india/india 15 and 5 days count.csv')
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,6]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))
lr.predict([[1155191,28084]])

Accuracy r2_score 99.74747669170905
ACCURACY= 99.80310116519838
MAE= 10777.742334932856
MSE= 168595891.15333894
Final rmse value is = 12984.448049622246


array([1903457.91698151])

SPAIN

In [24]:
df=pd.read_csv("/content/drive/MyDrive/Machine Learning Projects/covid data/spain/spain 15 and 5.csv")
df.head(3)
x=df.iloc[:,[3,4]]
y=df.iloc[:,6]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from math import sqrt
accuracy=r2_score(y_pred,y_test)*100
print("Accuracy r2_score",accuracy)
print("ACCURACY=",lr.score(x_train,y_train)*100)
from sklearn.metrics import mean_absolute_error
pred= lr.predict(x_test)
print("MAE=",mean_absolute_error(y_test, pred))
rss=((y_test-y_pred)**2).sum()
mse=np.mean((y_test-y_pred)**2)
print("MSE=",mse)
print("Final rmse value is =",np.sqrt(np.mean((y_test-y_pred)**2)))
lr.predict([[264836,28422]])

Accuracy r2_score 97.19751200065959
ACCURACY= 96.17662698227204
MAE= 14131.890427119757
MSE= 309895111.87746376
Final rmse value is = 17603.83798713973


array([300939.63598831])